Repository SMUMC-7th/7th_Spring, pull requests merged in 2024-11, with the labels that each got.

#84 ✨ [Feat] 페이지네이션 기능 구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/converter/ReplyConverter.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#77 ✨ [Feat] 페이지네이션 기능 구현
  src/main/java/com/example/umc7th/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#83 ✨ [Feat] 페이지네이션 기능 구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/exception/ArticleErrorCode.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#97 ✨ [feat] 페이지네이션 기능구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/controller/ArticleSearchCond.java
  src/main/java/com/example/umc7th/domain/article/converter/ArticleConverter.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/converter/ReplyConverter.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#89 ✨ [Feat] 페이지네이션 기능 구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/converter/ArticleConverter.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/entity/Article.java
  src/main/java/com/example/umc7th/domain/article/enums/ArticleSearchQuery.java
  src/main/java/com/example/umc7th/domain/article/exception/ArticleErrorCode.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/command/ArticleCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/converter/ReplyConverter.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/entity/Reply.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/command/ReplyCommandService.java
  src/main/java/com/example/umc7th/domain/reply/service/command/ReplyCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#95 ✨ [feat] 페이지네이션 기능구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/entity/Reply.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SwaggerConfig.java
Labels: ✨feature

#108 ✨ [FEAT] Jwt Filter, 회원가입, 로그인 구현
  build.gradle
  src/main/java/com/example/umc7th/controller/MemberController.java
  src/main/java/com/example/umc7th/converter/MemberConverter.java
  src/main/java/com/example/umc7th/dto/request/MemberRequestDto.java
  src/main/java/com/example/umc7th/dto/response/MemberResponseDto.java
  src/main/java/com/example/umc7th/entity/Member.java
  src/main/java/com/example/umc7th/global/apipayload/code/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/apipayload/code/MemberErrorCode.java
  src/main/java/com/example/umc7th/global/apipayload/exception/AuthException.java
  src/main/java/com/example/umc7th/global/apipayload/exception/MemberException.java
  src/main/java/com/example/umc7th/global/jwt/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/global/jwt/userdetails/PrincipalDetails.java
  src/main/java/com/example/umc7th/global/jwt/userdetails/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/global/jwt/util/JwtProvider.java
  src/main/java/com/example/umc7th/repository/MemberRepository.java
  src/main/java/com/example/umc7th/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/service/query/MemberQueryService.java
  src/main/java/com/example/umc7th/service/query/MemberQueryServiceImpl.java
Labels: ✨feature

#116 ✨ [Feat] Security, 로그인, 회원가입 구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/converter/MemberConverter.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberException.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryService.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/exception/AuthException.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/global/jwt/principal/PrincipalDetails.java
  src/main/java/com/example/umc7th/global/jwt/principal/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/global/jwt/util/JwtProvider.java
  src/main/resources/application.yml
Labels: ✨feature

#113 ✨ [Feat] Spring Security, 로그인 및 회원가입 기능 구현
  build.gradle
  src/main/java/com/example/umc7th/article/exception/ArticleErrorCode.java
  src/main/java/com/example/umc7th/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/example/umc7th/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/exception/AuthException.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/global/jwt/util/JwtProvider.java
  src/main/java/com/example/umc7th/member/controller/MemberController.java
  src/main/java/com/example/umc7th/member/dto/MemberRequestDTO.java
  src/main/java/com/example/umc7th/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/member/entity/Member.java
  src/main/java/com/example/umc7th/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/member/exception/MemberException.java
  src/main/java/com/example/umc7th/member/principal/PrincipalDetails.java
  src/main/java/com/example/umc7th/member/principal/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/member/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/reply/exception/ReplyErrorCode.java
Labels: ✨feature, ♻️refactor

#101 ✨ [feat] 페이지네이션 기능구현
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/converter/ReplyConverter.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
Labels: ✨feature

#124 :sparkles: [feat] security,로그인,회원가입구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/config/SecurityConfig.java
  src/main/java/com/example/umc7th/domain/member/controller/MemberControlloer.java
  src/main/java/com/example/umc7th/domain/member/converter/MemberConverter.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberDto.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/jwt/JwtFilter.java
  src/main/java/com/example/umc7th/domain/member/jwt/JwtProvider.java
  src/main/java/com/example/umc7th/domain/member/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/domain/member/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/domain/member/jwt/userdetails/PrincipalDetails.java
  src/main/java/com/example/umc7th/domain/member/jwt/userdetails/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryService.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/resources/application.yml
Labels: ✨feature

#120 ✨ [Feat] Security, 로그인 및 회원가입 구현
  build.gradle
  src/main/java/com/example/umc7th/Time.java
  src/main/java/com/example/umc7th/domain/article/entity/Article.java
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberException.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/MemberCommandService.java
  src/main/java/com/example/umc7th/domain/member/service/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/test/TestController.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/config/SwaggerConfig.java
  src/main/java/com/example/umc7th/global/jwt/exception/AuthException.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/filter/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/userDetails/PrincipalDetails.java
  src/main/java/com/example/umc7th/global/jwt/userDetails/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/global/util/JwtProvider.java
  src/main/resources/application.yml
Labels: ✨feature

#118 ✨ [Feat] Security, 로그인 및 회원가입 구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/converter/MemberConverter.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberException.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryService.java
  src/main/java/com/example/umc7th/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/JwtProvider.java
  src/main/java/com/example/umc7th/global/jwt/exception/AuthException.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/userdetails/PrincipalDetails.java
  src/main/java/com/example/umc7th/global/jwt/userdetails/PrincipalDetailsService.java
  src/main/resources/application.yml
Labels: ✨feature

#126 ✨feat: 카카오 로그인 구현
  build.gradle
  src/main/java/com/example/umc7th/controller/OAuth2Controller.java
  src/main/java/com/example/umc7th/dto/OAuth2Dto.java
  src/main/java/com/example/umc7th/global/apipayload/code/MemberErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/config/SecurityConfig.java
  src/main/java/com/example/umc7th/service/command/OAuth2Service.java
  src/main/java/com/example/umc7th/service/command/OAuth2ServiceImpl.java
Labels: ✨feature

#144 ✨feat: OAuth2 로그인 구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/converter/MemberConverter.java
  src/main/java/com/example/umc7th/domain/member/dto/response/MemberResDto.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/oauth2/controller/OAuth2Controller.java
  src/main/java/com/example/umc7th/domain/oauth2/dto/OAuth2Dto.java
  src/main/java/com/example/umc7th/domain/oauth2/service/OAuth2Service.java
  src/main/java/com/example/umc7th/domain/oauth2/service/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/dto/AuthUser.java
  src/main/java/com/example/umc7th/global/jwt/userDetails/PrincipalDetails.java
Labels: ✨feature

#147 ✨ [Feat] OAuth2 Login 구현
  build.gradle
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/config/WebClientConfig.java
  src/main/java/com/example/umc7th/kakao/controller/KakaoController.java
  src/main/java/com/example/umc7th/kakao/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/kakao/service/OAuth2Service.java
  src/main/java/com/example/umc7th/kakao/service/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/member/controller/MemberController.java
  src/main/java/com/example/umc7th/member/enums/SocialType.java
  src/main/java/com/example/umc7th/member/exception/MemberErrorCode.java
Labels: ✨feature

#131 ✨ [Feat] OAuth2 Login 구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/controller/OAuth2Controller.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberResDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/domain/member/enums/SocialType.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/member/service/command/OAuth2Service.java
  src/main/java/com/example/umc7th/domain/member/service/command/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨feature

#140 ✨ [Feat] OAuth2 Login
  build.gradle
  src/main/java/com/example/umc7th/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/oauth/controller/OAuth2Controller.java
  src/main/java/com/example/umc7th/domain/oauth/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/umc7th/domain/oauth/service/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ✨feature

#160 ✨feat: Open Api 사용 구현
  build.gradle
  src/main/java/com/example/umc7th/openApi/OpenApiWebClient.java
  src/main/java/com/example/umc7th/openApi/OpenApiWebClientImpl.java
  src/main/java/com/example/umc7th/openApi/controller/OpenApiController.java
  src/main/java/com/example/umc7th/openApi/dto/OpenApiResponseDTO.java
  src/main/java/com/example/umc7th/openApi/exception/OpenApiErrorCode.java
  src/main/java/com/example/umc7th/openApi/exception/OpenApiException.java
  src/main/java/com/example/umc7th/openApi/service/OpenApiQueryService.java
  src/main/java/com/example/umc7th/openApi/service/OpenApiQueryServiceImpl.java
Labels: ✨feature

#134 ✨ [Feat] OAuth2 Login 구현
  build.gradle
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/oauth/controller/OauthController.java
  src/main/java/com/example/umc7th/domain/oauth/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/domain/oauth/service/OAuth2Service.java
  src/main/java/com/example/umc7th/domain/oauth/service/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨feature

#135 ✨ [feat]OAuth2 login 구현
  .gitignore
  build.gradle
  src/main/java/com/example/umc7th/Umc7thApplication.java
  src/main/java/com/example/umc7th/domain/article/controller/ArticleController.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleRequestDTO.java
  src/main/java/com/example/umc7th/domain/article/dto/ArticleResponseDTO.java
  src/main/java/com/example/umc7th/domain/article/entity/Article.java
  src/main/java/com/example/umc7th/domain/article/exception/ArticleErrorCode.java
  src/main/java/com/example/umc7th/domain/article/exception/ArticleException.java
  src/main/java/com/example/umc7th/domain/article/repository/ArticleRepository.java
  src/main/java/com/example/umc7th/domain/article/service/command/ArticleCommandService.java
  src/main/java/com/example/umc7th/domain/article/service/command/ArticleCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryService.java
  src/main/java/com/example/umc7th/domain/article/service/query/ArticleQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/example/umc7th/domain/member/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/umc7th/domain/member/exception/MemberException.java
  src/main/java/com/example/umc7th/domain/member/principal/PrincipalDetails.java
  src/main/java/com/example/umc7th/domain/member/principal/PrincipalDetailsService.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/OAuth2/OAuth2Service.java
  src/main/java/com/example/umc7th/domain/member/service/OAuth2/OAuth2ServiceImpl.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandService.java
  src/main/java/com/example/umc7th/domain/member/service/command/MemberCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/controller/ReplyController.java
  src/main/java/com/example/umc7th/domain/reply/converter/ReplyConverter.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyRequestDTO.java
  src/main/java/com/example/umc7th/domain/reply/dto/ReplyResponseDTO.java
  src/main/java/com/example/umc7th/domain/reply/entity/Reply.java
  src/main/java/com/example/umc7th/domain/reply/exception/ReplyErrorCode.java
  src/main/java/com/example/umc7th/domain/reply/exception/ReplyException.java
  src/main/java/com/example/umc7th/domain/reply/repository/ReplyRepository.java
  src/main/java/com/example/umc7th/domain/reply/service/command/ReplyCommandService.java
  src/main/java/com/example/umc7th/domain/reply/service/command/ReplyCommandServiceImpl.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryService.java
  src/main/java/com/example/umc7th/domain/reply/service/query/ReplyQueryServiceImpl.java
  src/main/java/com/example/umc7th/domain/test/TestController.java
  src/main/java/com/example/umc7th/global/apiPayload/CustomResponse.java
  src/main/java/com/example/umc7th/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/example/umc7th/global/apiPayload/code/BaseSuccessCode.java
  src/main/java/com/example/umc7th/global/apiPayload/code/GeneralErrorCode.java
  src/main/java/com/example/umc7th/global/apiPayload/code/GeneralSuccessCode.java
  src/main/java/com/example/umc7th/global/apiPayload/exception/CustomException.java
  src/main/java/com/example/umc7th/global/apiPayload/exception/handler/ExceptionAdvice.java
  src/main/java/com/example/umc7th/global/common/BaseEntity.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/JwtFilter.java
  src/main/java/com/example/umc7th/global/jwt/JwtProvider.java
  src/main/java/com/example/umc7th/global/jwt/exception/AuthException.java
  src/main/java/com/example/umc7th/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/umc7th/global/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/resources/application.yml
Labels: ✨feature

#172 ✨ [Feat] 1주차부터 8주차 코드 (Git Conflict 실습)
  build.gradle
  src/main/java/com/example/umc7th/domain/member/controller/MemberController.java
  src/main/java/com/example/umc7th/domain/member/dto/OAuth2DTO.java
  src/main/java/com/example/umc7th/domain/member/entity/Member.java
  src/main/java/com/example/umc7th/domain/member/repository/MemberRepository.java
  src/main/java/com/example/umc7th/domain/member/service/command/OAuth2LibraryService.java
  src/main/java/com/example/umc7th/domain/openapi/controller/OpenApiController.java
  src/main/java/com/example/umc7th/domain/openapi/dto/OpenApiResponseDTO.java
  src/main/java/com/example/umc7th/domain/openapi/exception/OpenApiErrorCode.java
  src/main/java/com/example/umc7th/domain/openapi/exception/OpenApiException.java
  src/main/java/com/example/umc7th/domain/openapi/service/query/OpenApiQueryService.java
  src/main/java/com/example/umc7th/domain/openapi/service/query/OpenApiQueryServiceImpl.java
  src/main/java/com/example/umc7th/global/config/SecurityConfig.java
  src/main/java/com/example/umc7th/global/jwt/handler/OAuth2SuccessfulHandler.java
  src/main/java/com/example/umc7th/global/openapi/OpenApiWebClient.java
  src/main/java/com/example/umc7th/global/openapi/OpenApiWebClientImpl.java
  src/main/resources/application.yml
Labels: 🐛bug, ✨feature
